In [9]:
import pandas as pd

In [10]:
artists_df = pd.read_csv('Artists.csv')
artworks_df = pd.read_csv('Artworks.csv')
art_on_view_df = pd.read_excel('MoMA_OnView.xlsx')

In [11]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [30]:
print(artists_df.shape)
artists_df.head(5)
artists_df.info()

(15638, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15638 entries, 0 to 15637
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ConstituentID  15638 non-null  object
 1   DisplayName    15638 non-null  object
 2   ArtistBio      13438 non-null  object
 3   Nationality    13142 non-null  object
 4   Gender         12381 non-null  object
 5   BeginDate      15638 non-null  int64
 6   EndDate        15638 non-null  int64
 7   Wiki QID       3247 non-null   object
 8   ULAN           2931 non-null   float64
dtypes: float64(1), int64(2), object(6)
memory usage: 1.1+ MB

In [14]:
print(artworks_df.shape)
artworks_df.head(3)

(157630, 30)

,Title,Artist,ConstituentID,ArtistBio,Nationality,BeginDate,EndDate,Gender,Date,Medium,Dimensions,CreditLine,AccessionNumber,Classification,Department,DateAcquired,Cataloged,ObjectID,URL,ImageURL,OnView,Circumference (cm),Depth (cm),Diameter (cm),Height (cm),Length (cm),Weight (kg),Width (cm),Seat Height (cm),Duration (sec.)
0,"Ferdinandsbrücke Project, Vienna, Austria (Ele...",Otto Wagner,6210,"(Austrian, 1841–1918)",(Austrian),(1841),(1918),(male),1896,Ink and cut-and-pasted painted pages on paper,"19 1/8 x 66 1/2"" (48.6 x 168.9 cm)",Fractional and promised gift of Jo Carole and ...,885.1996,Architecture,Architecture & Design,1996-04-09,Y,2,https://www.moma.org/collection/works/2,https://www.moma.org/media/W1siZiIsIjUyNzc3MCJ...,NaN,NaN,NaN,NaN,48.6000,NaN,NaN,168.9000,NaN,NaN
1,"City of Music, National Superior Conservatory ...",Christian de Portzamparc,7470,"(French, born 1944)",(French),(1944),(0),(male),1987,Paint and colored pencil on print,"16 x 11 3/4"" (40.6 x 29.8 cm)",Gift of the architect in honor of Lily Auchinc...,1.1995,Architecture,Architecture & Design,1995-01-17,Y,3,https://www.moma.org/collection/works/3,https://www.moma.org/media/W1siZiIsIjUyNzM3NCJ...,NaN,NaN,NaN,NaN,40.6401,NaN,NaN,29.8451,NaN,NaN
2,"Villa project, outside Vienna, Austria (Elevat...",Emil Hoppe,7605,"(Austrian, 1876–1957)",(Austrian),(1876),(1957),(male),1903,"Graphite, pen, color pencil, ink, and gouache ...","13 1/2 x 12 1/2"" (34.3 x 31.8 cm)",Gift of Jo Carole and Ronald S. Lauder,1.1997,Architecture,Architecture & Design,1997-01-15,Y,4,https://www.moma.org/collection/works/4,https://www.moma.org/media/W1siZiIsIjUyNzM3NSJ...,NaN,NaN,NaN,NaN,34.3000,NaN,NaN,31.8000,NaN,NaN

In [16]:
# Convert consituentID to string for merging
artists_df["ConstituentID"]= artists_df["ConstituentID"].astype(str)
artworks_df["ConstituentID"]= artworks_df["ConstituentID"].astype(str)
art_on_view_df["ConstituentID"]=art_on_view_df["ConstituentID"].astype(str)

In [32]:
# merge artworks dataset with Artists dataset on consituentID
merged_df = artworks_df.merge(artists_df, on="ConstituentID", how="left")
print(merged_df.shape)
merged_df.head(2)

(157630, 38)

,Title,Artist,ConstituentID,ArtistBio_x,Nationality_x,BeginDate_x,EndDate_x,Gender_x,Date,Medium,Dimensions,CreditLine,AccessionNumber,Classification,Department,DateAcquired,Cataloged,ObjectID,URL,ImageURL,OnView,Circumference (cm),Depth (cm),Diameter (cm),Height (cm),Length (cm),Weight (kg),Width (cm),Seat Height (cm),Duration (sec.),DisplayName,ArtistBio_y,Nationality_y,Gender_y,BeginDate_y,EndDate_y,Wiki QID,ULAN
0,"Ferdinandsbrücke Project, Vienna, Austria (Ele...",Otto Wagner,6210,"(Austrian, 1841–1918)",(Austrian),(1841),(1918),(male),1896,Ink and cut-and-pasted painted pages on paper,"19 1/8 x 66 1/2"" (48.6 x 168.9 cm)",Fractional and promised gift of Jo Carole and ...,885.1996,Architecture,Architecture & Design,1996-04-09,Y,2,https://www.moma.org/collection/works/2,https://www.moma.org/media/W1siZiIsIjUyNzc3MCJ...,NaN,NaN,NaN,NaN,48.6000,NaN,NaN,168.9000,NaN,NaN,Otto Wagner,"Austrian, 1841–1918",Austrian,male,1841.0,1918.0,Q84287,500016971.0
1,"City of Music, National Superior Conservatory ...",Christian de Portzamparc,7470,"(French, born 1944)",(French),(1944),(0),(male),1987,Paint and colored pencil on print,"16 x 11 3/4"" (40.6 x 29.8 cm)",Gift of the architect in honor of Lily Auchinc...,1.1995,Architecture,Architecture & Design,1995-01-17,Y,3,https://www.moma.org/collection/works/3,https://www.moma.org/media/W1siZiIsIjUyNzM3NCJ...,NaN,NaN,NaN,NaN,40.6401,NaN,NaN,29.8451,NaN,NaN,Christian de Portzamparc,"French, born 1944",French,male,1944.0,0.0,Q312838,500024982.0

In [26]:
# merge with Onview dataset to check which artworks are on display
merged_onview_df = merged_df.merge(art_on_view_df, on = "ConstituentID", how="left")
print(merged_onview_df.shape)
merged_onview_df.head(2)

(157630, 44)

,Title,Artist,ConstituentID,ArtistBio_x,Nationality_x,BeginDate_x,EndDate_x,Gender_x,Date,Medium,Dimensions,CreditLine,AccessionNumber,Classification,Department,DateAcquired,Cataloged,ObjectID,URL,ImageURL,OnView,Circumference (cm),Depth (cm),Diameter (cm),Height (cm),Length (cm),Weight (kg),Width (cm),Seat Height (cm),Duration (sec.),DisplayName_x,ArtistBio_y,Nationality_y,Gender_y,BeginDate_y,EndDate_y,Wiki QID,ULAN,DisplayName_y,ArtistBio,Nationality,Gender,BeginDate,EndDate
0,"Ferdinandsbrücke Project, Vienna, Austria (Ele...",Otto Wagner,6210,"(Austrian, 1841–1918)",(Austrian),(1841),(1918),(male),1896,Ink and cut-and-pasted painted pages on paper,"19 1/8 x 66 1/2"" (48.6 x 168.9 cm)",Fractional and promised gift of Jo Carole and ...,885.1996,Architecture,Architecture & Design,1996-04-09,Y,2,https://www.moma.org/collection/works/2,https://www.moma.org/media/W1siZiIsIjUyNzc3MCJ...,NaN,NaN,NaN,NaN,48.6000,NaN,NaN,168.9000,NaN,NaN,Otto Wagner,"Austrian, 1841–1918",Austrian,male,1841.0,1918.0,Q84287,500016971.0,Otto Wagner,"Austrian, 1841–1918",Austrian,male,1841.0,1918.0
1,"City of Music, National Superior Conservatory ...",Christian de Portzamparc,7470,"(French, born 1944)",(French),(1944),(0),(male),1987,Paint and colored pencil on print,"16 x 11 3/4"" (40.6 x 29.8 cm)",Gift of the architect in honor of Lily Auchinc...,1.1995,Architecture,Architecture & Design,1995-01-17,Y,3,https://www.moma.org/collection/works/3,https://www.moma.org/media/W1siZiIsIjUyNzM3NCJ...,NaN,NaN,NaN,NaN,40.6401,NaN,NaN,29.8451,NaN,NaN,Christian de Portzamparc,"French, born 1944",French,male,1944.0,0.0,Q312838,500024982.0,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# Convert DateAcquired to datatime format for time-based analysis
merged_df["DateAcquired"] = pd.to_datetime(merged_df["DateAcquired"], errors='coerce')
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157630 entries, 0 to 157629
Data columns (total 38 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Title               157582 non-null  object
 1   Artist              156361 non-null  object
 2   ConstituentID       157630 non-null  object
 3   ArtistBio_x         151542 non-null  object
 4   Nationality_x       156361 non-null  object
 5   BeginDate_x         156361 non-null  object
 6   EndDate_x           156361 non-null  object
 7   Gender_x            156361 non-null  object
 8   Date                155611 non-null  object
 9   Medium              148383 non-null  object
 10  Dimensions          148971 non-null  object
 11  CreditLine          156080 non-null  object
 12  AccessionNumber     157630 non-null  object
 13  Classification      157630 non-null  object
 14  Department          157630 non-null  object
 15  DateAcquired        150881 non-null  datetime64[ns]
 16  Cataloged           157630 non-null  object
 17  ObjectID            157630 non-null  int64
 18  URL                 100231 non-null  object
 19  ImageURL            91043 non-null   object
 20  OnView              1210 non-null    object
 21  Circumference (cm)  10 non-null      float64
 22  Depth (cm)          18046 non-null   float64
 23  Diameter (cm)       1469 non-null    float64
 24  Height (cm)         128219 non-null  float64
 25  Length (cm)         725 non-null     float64
 26  Weight (kg)         296 non-null     float64
 27  Width (cm)          127293 non-null  float64
 28  Seat Height (cm)    0 non-null       float64
 29  Duration (sec.)     1953 non-null    float64
 30  DisplayName         148445 non-null  object
 31  ArtistBio_y         143754 non-null  object
 32  Nationality_y       143229 non-null  object
 33  Gender_y            140695 non-null  object
 34  BeginDate_y         148445 non-null  float64
 35  EndDate_y           148445 non-null  float64
 36  Wiki QID            110103 non-null  object
 37  ULAN                108594 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(1), object(24)
memory usage: 45.7+ MB

In [38]:
merged_onview_df['Classification'].value_counts().head(3)

Classification
Photograph          34770
Print               32590
Illustrated Book    27834
Name: count, dtype: int64

In [43]:
# Analysis

num_of_unique_artists = merged_df["DisplayName"].nunique()  # count of unique artists
top_nationalities = merged_df["Nationality_x"].value_counts().head(10) # top 10 nationalities
gender_counts = merged_df["Gender_y"].value_counts() # gender distribution
top_classification = merged_df["Classification"].value_counts().head(10) # top 10 artwork calssifications
department_counts = merged_df["Department"].value_counts() # Artworks per department
acquisition_trends = merged_df["DateAcquired"].dt.year.value_counts().sort_index() # Artworks acquired per year
top_artists = merged_df["DisplayName"].value_counts().head(10) # Top artists with most artworks
num_on_display = merged_onview_df["OnView"].notna().sum()  #count of artworks currently on display

In [50]:
print(acquisition_trends)

DateAcquired
1929.0        9
1930.0        7
1931.0        3
1932.0       18
1933.0       93
1934.0      284
1935.0      416
1936.0      146
1937.0      322
1938.0      127
1939.0      398
1940.0     1583
1941.0      977
1942.0      938
1943.0     1132
1944.0      346
1945.0      315
1946.0      171
1947.0      475
1948.0      421
1949.0     1588
1950.0      453
1951.0      631
1952.0      550
1953.0      474
1954.0      881
1955.0      446
1956.0     1134
1957.0      303
1958.0      705
1959.0      829
1960.0      449
1961.0      552
1962.0      565
1963.0      951
1964.0    12998
1965.0     2020
1966.0     1859
1967.0     2420
1968.0    19733
1969.0     2194
1970.0     1245
1971.0     1041
1972.0      862
1973.0     1101
1974.0     3394
1975.0      991
1976.0      902
1977.0     1208
1978.0     1349
1979.0     1198
1980.0      680
1981.0     1347
1982.0      851
1983.0     1157
1984.0      869
1985.0     1050
1986.0     1028
1987.0     1321
1988.0     1019
1989.0      891
1990.0     1274
1991.0      837
1992.0     1197
1993.0     1227
1994.0      943
1995.0      988
1996.0      972
1997.0      950
1998.0     1292
1999.0     1808
2000.0     1886
2001.0     4170
2002.0      635
2003.0      596
2004.0      773
2005.0     4054
2006.0     1665
2007.0     2348
2008.0     7176
2009.0     1531
2010.0     2050
2011.0     1916
2012.0     2943
2013.0     3109
2014.0     2829
2015.0     3817
2016.0     1994
2017.0     1620
2018.0     2507
2019.0     2286
2020.0     2600
2021.0      920
2022.0     1218
2023.0      468
2024.0      862
Name: count, dtype: int64

In [55]:
# calculating percentage distribution
department_percentage = merged_df['Department'].value_counts(normalize=True) * 100
department_percentage

Department
Drawings & Prints                        51.018207
Architecture & Design                    21.323352
Photography                              21.320815
Painting & Sculpture                      2.572480
Media and Performance                     2.028802
Fluxus Collection                         1.067690
Film                                      0.649623
Architecture & Design - Image Archive     0.019032
Name: proportion, dtype: float64

In [57]:
# filter the dataframe for DateAcquired after the year 2000
filtered_df = merged_df[merged_df["DateAcquired"].dt.year > 2000]

# get the count of DateAcquired values per year
date_acquired_counts = filtered_df['DateAcquired'].dt.year.value_counts().sort_index()

print(date_acquired_counts)

DateAcquired
2001    4170
2002     635
2003     596
2004     773
2005    4054
2006    1665
2007    2348
2008    7176
2009    1531
2010    2050
2011    1916
2012    2943
2013    3109
2014    2829
2015    3817
2016    1994
2017    1620
2018    2507
2019    2286
2020    2600
2021     920
2022    1218
2023     468
2024     862
Name: count, dtype: int64

In [58]:
artworks_df['OnView'].value_counts()

OnView
"MoMA, Floor 3, 3 East"              128
"MoMA, Floor 1, 1 South"              47
"MoMA, Floor 5, 503"                  46
"MoMA, Floor 3, 3 South"              41
"MoMA, Floor 5, 501"                  40
"MoMA, Floor 2, 216"                  40
"MoMA, Floor 4, 417"                  35
"MoMA, Floor 2, 2 South"              34
"MoMA, Floor 5, 521"                  34
"MoMA, Floor 5, 514"                  34
"MoMA, Floor 5, 517"                  32
"MoMA, Floor 5, 520"                  31
"MoMA, Floor 4, 409"                  31
"MoMA, Floor 5, 504"                  29
"MoMA, Floor 5, 511"                  27
"MoMA, Floor 5, 519"                  26
"MoMA, Floor 4, 402"                  26
"MoMA, Floor 5, 505"                  24
"MoMA, Floor 5, 513"                  24
"MoMA, Floor 5, 516"                  23
"MoMA, Floor 4, 419"                  23
"MoMA, Floor 5, 506"                  20
"MoMA, Floor 5, 522"                  20
"MoMA, Floor 5, 512"                  18
"MoMA, Floor 4, 405"                  18
"MoMA, Floor 4, 413"                  18
"MoMA, Floor 4, 420"                  17
"MoMA, Floor 5, 510"                  17
"MoMA, Floor 4, 410"                  16
"MoMA, Floor 4, 412"                  16
"MoMA, Floor 1, Sculpture Garden"     16
"MoMA, Floor 5, 507"                  15
"MoMA, Floor 5, 509"                  15
"MoMA, Floor 4, 407"                  13
"MoMA, Floor 2, 214"                  13
"MoMA, Floor 4, 408"                  12
"MoMA, Floor 1"                       12
"MoMA, Floor 5, 508"                  12
"MoMA, Floor 4, 406"                  12
"MoMA, Floor 4, 401"                  11
"MoMA, Floor 4, 404"                  11
"MoMA, Floor 4, 415"                  10
"MoMA, Floor 4, 416"                  10
"MoMA, Floor 5, 502"                   9
"MoMA, Floor 2, 208"                   8
"MoMA, Floor 2, 215"                   8
"MoMA, Floor 2, 203"                   7
"MoMA, Floor 5, 500"                   6
"MoMA, Floor 2"                        6
"MoMA, Floor 4, 403"                   6
"MoMA, Floor 2, 205"                   5
"MoMA, Floor 4, 421"                   5
"MoMA, Floor 2, 206"                   5
"MoMA, Floor 2, 209"                   5
"MoMA, Floor 5"                        5
"MoMA, Floor 2, 202"                   5
"MoMA, Floor 5, 523"                   5
"MoMA, Floor 4"                        4
"MoMA, Floor 3"                        3
"MoMA, Floor 5, 515"                   3
"MoMA, Floor 2, 201"                   3
"MoMA, Floor 4, 414"                   3
"MoMA, Floor 6"                        2
"MoMA, Floor 5, 518"                   1
"MoMA, Floor 4, 418"                   1
"MoMA, Floor 2, 207"                   1
"MoMA, Floor 4, 400"                   1
"MoMA, Floor 2, 210"                   1
"MoMA, Floor 1, Art Lab"               1
"MoMA PS1, Third floor"                1
"MoMA, Floor 2, 213"                   1
"MoMA, Floor 2, 204"                   1
"MoMA, Floor 2, 211"                   1
Name: count, dtype: int64

In [64]:
import plotly.express as px

# visualization using plotly
fig1 = px.bar(x=top_nationalities.index, y=top_nationalities.values,
             title="Top 10 Nationalities of Artists in MoMa",
             labels={"x": "Nationality", "y": "Number of Artists"},
             color=top_nationalities.values)
fig1.show()

In [66]:
# visualization using plotly
fig2 = px.bar(x=gender_counts.index, y=gender_counts.values,
             title="Gender distribution of Artists",
             labels={"x": "Gender", "y": "Number of Artists"},
             color=gender_counts.values)
fig2.show()

In [69]:
# visualization using plotly
fig3 = px.line(x=acquisition_trends.index, y=acquisition_trends.values,
             title="MoMa Artwork Acquisitions Over time",
             labels={"x": "Year", "y": "Number of Artworks Acquired"},
             markers=True)
fig3.show()